---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rabe-github-actions
  description: RaBe GitHub Actions
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: radiorabe/actions
  links:
    - url: https://radiorabe.github.io/actions/
      title: Documentation
      icon: docs
    - url: https://radiorabe.github.io/actions/contributing/
      title: Contributing Guide
      icon: help
spec:
  type: library
  lifecycle: experimental
  owner: it-reaktion
  system: rabe-github
