site_name: RaBe GitHub Actions
site_url: https://radiorabe.github.io/actions/
repo_url: https://github.com/radiorabe/actions
repo_name: radiorabe/actions

theme:
  name: "material"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

extra_css:
- css/style.css

plugins:
- search
- section-index

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Workflows:
    - workflows/index.md
    - Ansible Collections:
      - workflows/ansible/index.md
      - Release: workflows/ansible/release.md
      - Test: workflows/ansible/test.md
    - Container Images:
      - workflows/container/index.md
      - Release: workflows/container/release.md
      - Schedule: workflows/container/schedule.md
    - Python:
      - workflows/python/index.md
      - Test: workflows/python/test.md
      - Release: workflows/python/release.md
    - Pre-Commit: workflows/pre-commit.md
    - MkDocs: workflows/mkdocs.md
    - Semantic Release: workflows/semantic-release.md
  - Permissions: permissions.md
