name: Release

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      # Used to authenticate to PyPI via OIDC.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write
      # For Pages (in addition to contents write)
      pages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - run: poetry install

      - run: poetry version $(git describe --tags --abbrev=0 --exact-match || (git describe --tags --abbrev=0 --dirty=+dev|tr -d '\n'; echo "+dev"))

      - run: poetry build --no-interaction

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          verbose: true
          print-hash: true
        if: ${{ github.event_name == 'release' }}

      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
        if: ${{ github.event_name == 'release' }}

      - run: poetry run mkdocs gh-deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
