name: Release Mkdocs

on:
  workflow_call:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  publish:
    name: Publish Mkdocs documentation to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write # for pushing gh-pages branch

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          # credentials are reused by the mdocs gh-deploy step for now
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install Mkdocs and plugins
        run: pip install "mkdocs<2.0" mkdocs-material mkdocs-gen-files mkdocs-literate-nav mkdocs-section-index mkdocs-autorefs 'mkdocstrings[python]' mkdocs-llmstxt

      - name: Build Mkdocs documentation
        run: mkdocs build

      - name: Deploy Mkdocs documentation
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: mkdocs gh-deploy
