name: Release

on:
  workflow_call:
    inputs:
      path:
        description: "path to the directory containing pyproject.toml"
        required: false
        default: "."
        type: string
    secrets:
      RABE_PYPI_TOKEN:
        required: false

permissions: {}

jobs:
  publish:
    name: Publish Python Package
    runs-on: ubuntu-latest

    permissions:
      contents: write # for pushing gh-pages branch

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          # credentials are reused by the mkdocs gh-deploy step for now
          persist-credentials: true

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install
        working-directory: ${{ inputs.path }}

      - name: Configure poetry
        if: ${{ github.event_name == 'release' }}
        env:
          RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
        run: poetry config pypi-token.pypi "${RABE_PYPI_TOKEN}"
        working-directory: ${{ inputs.path }}

      - name: Set dry-run flag
        id: dry-run
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          flag="--dry-run"
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            flag=""
          fi
          echo "flag=$flag" >> $GITHUB_OUTPUT

      - name: Set version in pyproject.toml for release
        run: poetry version $(git describe --tags --abbrev=0 --exact-match || (git describe --tags --abbrev=0 --dirty=+dev|tr -d '\n'; echo "+dev"))
        working-directory: ${{ inputs.path }}

      - name: Publish to PyPI
        env:
          POETRY_DRY_RUN: ${{ steps.dry-run.outputs.flag }}
        run: poetry publish --build --no-interaction "${POETRY_DRY_RUN}"
        working-directory: ${{ inputs.path }}

      - name: Deploy documentation
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: poetry run mkdocs gh-deploy
        working-directory: ${{ inputs.path }}
