name: Release Ansible Collection
on:
  workflow_call:
    inputs:
      publish:
        description: 'Enable publishing collection'
        default: true
        required: false
        type: boolean
    secrets:
      GALAXY_API_KEY:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install ansible>=2
      - name: Update version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i -e "s/version: 0.0.0/version: ${VERSION}/" galaxy.yml
      - name: Build collection
        run: |
          ansible-galaxy collection build
      - name: Publish collection
        run: |
          ansible-galaxy collection publish *.tar.gz --token=${{ secrets.GALAXY_API_KEY }}
