name: Release Ansible Collection
on:
  workflow_call:
    inputs:
      publish:
        description: "Enable publishing collection"
        default: true
        required: false
        type: boolean
      path:
        description: "Path to the collection root (directory containing galaxy.yml)"
        required: false
        default: "."
        type: string
    secrets:
      GALAXY_API_KEY:
        required: false

permissions: {}

jobs:
  build:
    name: Build and optionally publish Ansible collection
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install ansible>=2

      - name: Update version
        if: startsWith(github.ref, 'refs/tags/')
        env:
          INPUTS_PATH: ${{ inputs.path }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i -e "s/version: 0.0.0/version: ${VERSION}/" "${INPUTS_PATH}/galaxy.yml"

      - name: Build collection
        env:
          INPUTS_PATH: ${{ inputs.path }}
        run: |
          ansible-galaxy collection build "${INPUTS_PATH}"

      - name: Publish collection
        if: inputs.publish
        run: |
          ansible-galaxy collection publish *.tar.gz --token "${GALAXY_API_KEY}"
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
