name: Release Zensical

on:
  workflow_call:
    inputs:
      deploy:
        description: Deploy to GitHub Pages
        type: boolean
        default: true
      requirements:
        description: Extra Python packages to install alongside Zensical (space-separated)
        type: string
        default: ""
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    name: Build Zensical documentation
    runs-on: ubuntu-latest

    permissions:
      contents: read # to checkout the repository

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install Zensical
        run: pip install zensical ${INPUTS_REQUIREMENTS}
        env:
          INPUTS_REQUIREMENTS: ${{ inputs.requirements }}

      - name: Build Zensical documentation
        run: zensical build

      - name: Upload GitHub Pages artifact
        if: ${{ inputs.deploy && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: site

  deploy:
    name: Deploy Zensical documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.deploy && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write # to deploy to GitHub Pages
      id-token: write # to authenticate with GitHub Pages via OIDC

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
