name: Release Container Image

on:
  workflow_call:
    inputs:
      image:
        description: "image to build and push"
        required: true
        type: string
      name:
        description: "name for the name label"
        required: true
        type: string
      display-name:
        description: "display name for the io.k8s.display-name label"
        required: true
        type: string
      tags:
        description: "tags for the io.openshift.tags label"
        required: true
        type: string
      cosign-verify:
        description: "enable cosign verification"
        required: false
        default: true
        type: boolean
      cosign-certificate-oidc-issuer:
        description: "issuer used for keyless signature verification"
        required: false
        default: "https://token.actions.githubusercontent.com"
        type: string
      cosign-certificate-identity-regexp:
        description: "regex to verify the subject against"
        required: false
        default: "https://github.com/radiorabe/.*"
        type: string
      cosign-image-skip-regexp:
        description: "Regex to exclude some images from cosign image scan"
        required: false
        default: "#"
        type: string
      cosign-base-image-only:
        description: "DEPRECATED: not supported by cosign verify"
        required: false
        default: false
        type: boolean
      dockerfile:
        description: "Path to the Dockerfile used in the build"
        required: false
        default: "Dockerfile"
        type: string
      context:
        description: "Context directory for build"
        required: false
        default: "."
        type: string
      build-args:
        description: "Pass ARGs to the build"
        required: false
        default: ""
        type: string
      push-default-branch:
        description: "Push the default branch (typically `main`) to the registry."
        required: false
        default: false
        type: boolean
      pre-script:
        description: "Run a script before interacting with the Dockerfile. Take care not to run untrusted input in this script."
        required: false
        default: ""
        type: string
      platforms:
        description: "what platforms to build for (comma separated for multi-platform builds, e.g. linux/amd64,linux/arm64)"
        required: false
        default: "linux/amd64"
        type: string
      docker-daemon-config:
        description: "Config for setup-docker-action"
        required: false
        type: string

permissions: {}

jobs:
  docker:
    name: Build and Release Container Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # needed for pushing to GitHub Container Registry
      security-events: write # needed for uploading Trivy scan results to the Security tab
      id-token: write # needed for signing the images with GitHub OIDC using cosign

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Prepare additional Metadata
        id: additional_meta
        run: |
          echo created=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT

      - name: Prepare Image Metadata
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{ inputs.image }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            name=${{ inputs.name }}
            summary=${{ github.event.repository.description }}
            url=${{ github.event.repository.html_url }}
            vcs-ref=${{ github.sha }}
            revision=${{ github.sha }}
            release=${{ github.sha }}
            build-date=${{ steps.additional_meta.outputs.created }}
            io.k8s.display-name=${{ inputs.display-name }}
            io.k8s.description=${{ github.event.repository.description }}
            io.openshift.tags=${{ inputs.tags }}

      - name: Set up Docker
        if: inputs.docker-daemon-config
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0
        with:
          daemon-config: ${{ inputs.docker-daemon-config }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Run pre script
        if: inputs.pre-script != ''
        run: ${{ inputs.pre-script }} # zizmor: ignore[template-injection] - this is intended to allow running arbitrary scripts, but make sure to only use it with trusted input!

      - name: Verify ${{ inputs.dockerfile }} using cosign
        if: inputs.cosign-verify
        env:
          COSIGN_IMAGE_SKIP_REGEXP: ${{ inputs.cosign-image-skip-regexp }}
          COSIGN_CERTIFICATE_IDENTITY_REGEXP: ${{ inputs.cosign-certificate-identity-regexp }}
          COSIGN_CERTIFICATE_OIDC_ISSUER: ${{ inputs.cosign-certificate-oidc-issuer }}
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          set -euo pipefail
          cosign verify \
            --certificate-oidc-issuer "${COSIGN_CERTIFICATE_OIDC_ISSUER}" \
            --certificate-identity-regexp "${COSIGN_CERTIFICATE_IDENTITY_REGEXP}" \
          -- $(gawk 'BEGIN {IGNORECASE=1} match($0, /^\s*FROM\s+(--platform=\S+\s+)?(\S+)(\s+AS\s+(\S+))?/, a) {if (a[2] != "scratch") print a[2]; if (a[4] != "") s[a[4]] = 1; next} match($0, /^\s*COPY\s+.*--from=(\S+)/, a) {if (a[1] !~ /^[0-9]+$/ && a[1] != "scratch" && !(a[1] in s)) print a[1]}' ${DOCKERFILE} | grep -E -v -i ${COSIGN_IMAGE_SKIP_REGEXP}) > /dev/null

      - name: Build Container Image
        id: docker_build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          context: ${{ inputs.context }} # zizmor: ignore[template-injection] - this is intended to allow arbitrary build contexts, but make sure to only use it with trusted input!
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.build-args }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            version=${{ steps.meta.outputs.version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: "${{ inputs.image }}:${{ steps.meta.outputs.version }}"
          format: "json"
          ignore-unfixed: true
          list-all-pkgs: true
          output: "trivy.json"

      - name: Convert trivy results to sarif
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: trivy.json
          scan-type: "convert"
          format: "sarif"
          # we don't actually limit them, but this gates the convert action
          limit-severities-for-sarif: true
          # empty makes it skip the --vuln-type arg
          vuln-type: ""
          output: "trivy.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: always()
        with:
          sarif_file: "trivy.sarif"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Container Image
        id: docker_push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          CONTEXT: ${{ inputs.context }}
          DOCKER_CONTENT_TRUST: 1
        with:
          context: ${{ inputs.context }} # zizmor: ignore[template-injection] - this is intended to allow arbitrary build contexts, but make sure to only use it with trusted input!
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: ${{ github.event_name != 'pull_request' && (startsWith(github.event.ref, 'refs/tags/v') || inputs.push-default-branch &&  github.event.ref_name == github.event.repository.default_branch) }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          build-args: ${{ inputs.build-args }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            version=${{ steps.meta.outputs.version }}

      - name: Sign the images with GitHub OIDC Token using cosign
        if: github.event_name != 'pull_request' && startsWith(github.event.ref, 'refs/tags/v')
        run: cosign sign --yes -- "${IMAGE}@${STEPS_DOCKER_PUSH_OUTPUTS_DIGEST}"
        env:
          IMAGE: ${{ inputs.image }}
          STEPS_DOCKER_PUSH_OUTPUTS_DIGEST: ${{ steps.docker_push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}

      - name: Convert trivy results to CycloneDX
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: trivy.json
          scan-type: "convert"
          format: "cyclonedx"
          # we don't actually limit them, but this gates the convert action
          limit-severities-for-sarif: true
          # empty makes it skip the --vuln-type arg
          vuln-type: ""
          output: "trivy.cdx"

      - name: Attach an SBOM attestation to the signed image
        if: github.event_name != 'pull_request' && startsWith(github.event.ref, 'refs/tags/v')
        run: cosign attest --yes --type cyclonedx --predicate trivy.cdx -- "${IMAGE}@${STEPS_DOCKER_PUSH_OUTPUTS_DIGEST}"
        env:
          IMAGE: ${{ inputs.image }}
          STEPS_DOCKER_PUSH_OUTPUTS_DIGEST: ${{ steps.docker_push.outputs.digest }}

      - name: Convert trivy results to cosign-vuln
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: trivy.json
          scan-type: "convert"
          format: "cosign-vuln"
          # we don't actually limit them, but this gates the convert action
          limit-severities-for-sarif: true
          # empty makes it skip the --vuln-type arg
          vuln-type: ""
          output: "trivy.cosign.json"

      - name: Attach a security attestation to the signed image
        if: github.event_name != 'pull_request' && startsWith(github.event.ref, 'refs/tags/v')
        run: cosign attest --yes --type vuln --predicate trivy.cosign.json -- "${IMAGE}@${STEPS_DOCKER_PUSH_OUTPUTS_DIGEST}"
        env:
          IMAGE: ${{ inputs.image }}
          STEPS_DOCKER_PUSH_OUTPUTS_DIGEST: ${{ steps.docker_push.outputs.digest }}
