name: Release

on:
  workflow_call:
    secrets:
      RABE_PYPI_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - run: poetry install

      - name: Configure poetry
        run: poetry config pypi-token.pypi ${{ secrets.RABE_PYPI_TOKEN }}
        if: ${{ github.event_name == 'release' }}

      - name: Set dry-run flag
        id: dry-run
        run: |
          flag="--dry-run"
          if ${{ github.event_name == 'release' }}
          then
            flag=""
          fi
          echo "flag=$flag" >> $GITHUB_OUTPUT

      - run: poetry version $(git describe --tags --abbrev=0 --exact-match || (git describe --tags --abbrev=0 --dirty=+dev|tr -d '\n'; echo "+dev"))

      - run: poetry publish --build --no-interaction ${{ steps.dry-run.outputs.flag }}

      - run: poetry run mkdocs gh-deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
