name: Release Ansible Collection
on:
  workflow_call:
    inputs:
      publish:
        description: 'Enable publishing collection'
        default: true
        required: false
        type: boolean
    secrets:
      GALAXY_API_KEY:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install ansible>=2
      - name: Build collection
        run: |
          ansible-galaxy collection build
      - name: Publish collection
        run: |
          ansible-galaxy collection publish *.tar.gz --token=${{ secrets.GALAXY_API_KEY }}
