name: Run Trivy

on:
  workflow_call:
    inputs:
      image-ref:
        description: 'image-ref to scan'
        required: true
        type: string
      timeout:
        description: 'Scan timeout duration'
        required: false
        default: '5m0s'
        type: string

jobs:
  trivy:
    runs-on: ubuntu-latest

    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write # allow pushing attestation to registry
      pull-requests: none
      repository-projects: none
      security-events: write
      statuses: none
      id-token: write # needed for signing the images with GitHub OIDC using cosign

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: ${{ inputs.image-ref }}
          timeout: ${{ inputs.timeout }}
          format: 'json'
          ignore-unfixed: true
          list-all-pkgs: true
          scanners: 'vuln'
          output: 'trivy.json'

      - name: Convert trivy results to sarif
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: trivy.json
          scan-type: 'convert'
          format: 'sarif'
          # we don't actually limit them, but this gates the convert action
          limit-severities-for-sarif: true
          # empty makes it skip the --vuln-type arg
          vuln-type: ''
          output: 'trivy.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy.sarif'

      - name: Convert trivy results to cosign-vuln
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: trivy.json
          scan-type: 'convert'
          format: 'cosign-vuln'
          # we don't actually limit them, but this gates the convert action
          limit-severities-for-sarif: true
          # empty makes it skip the --vuln-type arg
          vuln-type: ''
          output: 'trivy.cosign.json'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach a security attestation to the signed image
        run: cosign attest --yes --type vuln --predicate trivy.cosign.json ${{ inputs.image-ref }}
