name: Run Trivy

on:
  workflow_call:
    inputs:
      image-ref:
        description: 'image-ref to scan'
        required: true
        type: string

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on latest
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-ref }}
          format: 'sarif'
          ignore-unfixed: true
          security-checks: 'vuln'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
