# runs on each push to main and is responsible for creating new tags/releases
name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      dry:
        description: "Run in dry-run mode (determine next version without creating a release)"
        required: false
        default: false
        type: boolean
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN:
        required: false

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        with:
          github-token: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          dry: ${{ inputs.dry || false }}
