# runs on each push to main and is responsible for creating new tags/releases
name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@v1.23
        with:
          github-token: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
          allow-initial-development-versions: true
