name: Lint and Test

on:
  workflow_call:
    inputs:
      version:
        description: "version to test against (in addition to latest 3.x)"
        required: false
        default: "3.12"
        type: string
      path:
        description: "path to the directory containing pyproject.toml"
        required: false
        default: "."
        type: string

permissions: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Test python ${{ matrix.python-version }}

    permissions:
      contents: read

    strategy:
      matrix:
        python-version: ["${{ inputs.version }}"]
        experimental: [false]
        include:
          - python-version: "3.x"
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry install
        working-directory: ${{ inputs.path }}

      - run: poetry run pip install pytest-github-actions-annotate-failures
        working-directory: ${{ inputs.path }}

      - run: poetry run pytest
        working-directory: ${{ inputs.path }}
