name: Lint and Test

on:
  workflow_call:
    inputs:
      path:
        description: Specific path to lint instead of the default `.`.
        required: false
        type: string
        default: "/github/workspace"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install --pre black
    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics
    - name: Lint with black
      run: black --check --diff .
    - name: Lint with ansible-lint
      uses: ansible/ansible-lint@v25.6.1
      with:
        setup_python: false
        working_directory: ${{ inputs.targets }}
