name: Lint and Test

on:
  workflow_call:
    inputs:
      requirements:
        description: Specific python packages to install with pip
        required: false
        type: string
        default: "black isort"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install ${{ inputs.requirements }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
